Document: libk8055
Title: Debian libk8055 Manual
Author: <insert document author here>
Abstract: This manual describes what libk8055 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libk8055/libk8055.sgml.gz

Format: postscript
Files: /usr/share/doc/libk8055/libk8055.ps.gz

Format: text
Files: /usr/share/doc/libk8055/libk8055.text.gz

Format: HTML
Index: /usr/share/doc/libk8055/html/index.html
Files: /usr/share/doc/libk8055/html/*.html

  
